### ISSUE TITLE
Image suggestions.

### ISSUE THREAD

**Issue by rv178** [XelphLinux/xelph-calamares-config-btrfs-git#1]
### #1

![](https://user-images.githubusercontent.com/69449141/134214930-ba4b10f5-89e8-4e53-bf72-0f46363685a9.png)

### #2

![](https://user-images.githubusercontent.com/69449141/134214941-b071bf84-558c-489f-872d-c6a2381266e9.png)

### #3

![](https://user-images.githubusercontent.com/69449141/134214945-4d70cf12-779a-445a-a050-e6dc983e9dd0.png)

### #4

![](https://user-images.githubusercontent.com/69449141/134214949-2dca88f9-2c79-4c79-9594-361412bfd0e8.png)

**Comment by Shinyzenith** [comment]
ty uwu
